"""Declarative base and shared column mixins.

The metadata naming convention is deliberately explicit. Without it Alembic
autogenerate produces anonymous constraint names (``ix_...``, ``fk_...``)
that PostgreSQL invents on the fly, which makes migrations impossible to
drop or alter deterministically later. Every index, foreign key, unique and
check constraint in SKYNET therefore has a predictable name.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import TypeEngine

# --------------------------------------------------------------------------
# Constraint naming
# --------------------------------------------------------------------------
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Shared declarative base for every SKYNET ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    #: Default SQL rendering for ``datetime`` annotations. Every timestamp in
    #: SKYNET is timezone-aware UTC; naive timestamps are never persisted.
    type_annotation_map: dict[type, TypeEngine] = {
        datetime: DateTime(timezone=True),
    }

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        identity = getattr(self, "id", None)
        if identity is None:
            identity = getattr(self, "event_id", None)
        return f"<{type(self).__name__} {identity!r}>"


class CreatedAtMixin:
    """Adds an immutable ``created_at`` stamp set by the database clock."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
        doc="Row insertion time, generated by the database server.",
    )


class TimestampMixin(CreatedAtMixin):
    """Adds ``created_at`` and a database-maintained ``updated_at``.

    ``updated_at`` uses ``onupdate`` at the ORM level and ``server_default``
    at the DDL level so rows touched by raw SQL still receive a value on
    insert. It is not an ``ON UPDATE`` trigger: SKYNET writes exclusively
    through the ORM for mutable tables.
    """

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        doc="Last modification time, refreshed by the ORM on update.",
    )
